import { test, expect, type Page } from '@playwright/test';
import { uniqueName } from './helpers';
import { createAccount, createBill } from './actions';

/** The main-list row (not the upcoming summary) for a schedule's payee. */
function scheduleRow(page: Page, payee: string) {
  // The schedule renders in both the upcoming summary and the main list; the
  // main-list row is the one carrying the Edit/Delete controls.
  return page
    .getByRole('listitem')
    .filter({ hasText: payee })
    .filter({ has: page.getByRole('button', { name: 'Edit' }) });
}

test.describe('Recurring & bills', () => {
  test('create a bill, see it listed, edit it, then delete it', async ({
    page,
  }) => {
    const account = uniqueName('E2E Bills Checking');
    const payee = uniqueName('E2E Netflix');

    await createAccount(page, account, 'checking', '1000.00');
    await createBill(page, {
      account,
      category: 'Groceries',
      payee,
      amount: '15.00',
      cadence: 'monthly',
    });

    // Listed as a bill (expense) with a negative signed amount.
    const row = scheduleRow(page, payee);
    await expect(row).toContainText('-$15.00');

    // Edit the amount.
    await row.getByRole('button', { name: 'Edit' }).click();
    await page.getByLabel('Amount ($)').fill('20.00');
    await page.getByRole('button', { name: 'Update' }).click();
    await expect(scheduleRow(page, payee)).toContainText('-$20.00');

    // Deep-link to the schedule's materialized transactions.
    await scheduleRow(page, payee).getByRole('link', { name: 'History' }).click();
    await expect(page).toHaveURL(/\/transactions\?recurringId=/);
    await expect(
      page.getByText(/generated by one recurring schedule/i),
    ).toBeVisible();

    // Delete the schedule via the confirm dialog.
    await page.goto('/recurring');
    await scheduleRow(page, payee).getByRole('button', { name: 'Delete' }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Delete' }).click();
    await expect(
      page.getByRole('listitem').filter({ hasText: payee }),
    ).toHaveCount(0);
  });
});
